### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/fleet#94]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] fleet_vehicle_calendar_year - By @kaynnan - #105
- [x] fleet_vehicle_configuration - By @kaynnan - #117
- [x] fleet_vehicle_fuel_capacity - By @kaynnan - #106
- [x] fleet_vehicle_fuel_type_ethanol - By @kaynnan - #107
- [x] fleet_vehicle_inspection - By @victoralmau - #140
- [x] fleet_vehicle_log_fuel - By @victoralmau - #142
- [x] fleet_vehicle_ownership - By @cubells - #183
- [x] fleet_vehicle_purchase - By @lmarion-source - #155
- [x] fleet_vehicle_service_activity - By @carolinafernandez-tecnativa - #143
- [x] fleet_vehicle_service_calendar - By @Alisson-Jns - #141
- [x] fleet_vehicle_service_kanban - By @kaynnan - #111
- [x] fleet_vehicle_service_services - By @kaynnan - #112
- [x] fleet_vehicle_stock - By @kaynnan - #108

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by AnizR** [comment]
Hello, I have done the migration of  fleet_vehicle_log_fuel  on #114

**Comment by amon-ra** [comment]
Why fleet_vehicle_inspection is not migrated?
